name: RHEL Shell Script Test

on: [push, pull_request]

jobs:
  execute-shell:
    # Uses GitHub's Red Hat Enterprise Linux image
    runs-on: self-hosted

    steps:
    - name: Pull code from GitHub
      uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x test.sh

    - name: Run my Shell tests
      run: ./test.sh
